# Generated by Django 5.2.4 on 2025-10-05 23:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('divisa_defecto', models.CharField(default='USD', help_text='Divisa por defecto de las listas de precios de este proveedor (ej. USD, EUR)', max_length=3)),
                ('tasa_cambio_usd_mxn', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Tipo de cambio específico de USD a MXN para este proveedor.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa_origen', models.CharField(help_text='Ej. USD', max_length=3, unique=True)),
                ('divisa_destino', models.CharField(default='MXN', help_text='Ej. MXN', max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor de 1 unidad de divisa_origen en divisa_destino', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión para usuarios anónimos.', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('user_display_name', models.CharField(blank=True, help_text='Nombre que el usuario proporcionó al iniciar el chat.', max_length=100, null=True)),
                ('initial_message_text', models.TextField(blank=True, help_text='Primer mensaje/duda inicial del usuario.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario registrado que inició la conversación, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_admin', models.BooleanField(default=False, help_text='True si el mensaje es del administrador.')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='productos.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_dolar', models.DecimalField(blank=True, decimal_places=2, help_text='Precio original del producto en la divisa del proveedor', max_digits=10, null=True)),
                ('inventario', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_imagenes/')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('compatibilidad', models.TextField(blank=True, null=True)),
                ('garantia_meses', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('num_nucleos', models.IntegerField(blank=True, null=True)),
                ('velocidad_ghz', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('memoria_gb', models.IntegerField(blank=True, null=True)),
                ('tipo_memoria', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_gb', models.IntegerField(blank=True, null=True)),
                ('velocidad_mhz', models.IntegerField(blank=True, null=True)),
                ('tipo_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProveedorPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
