# Generated by Django 5.2.4 on 2025-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tasa_cambio_usd_mxn',
            field=models.FloatField(default=18.0, help_text='Tasa de cambio específica de este proveedor'),
        ),
    ]
