# Generated by Django 5.2.4 on 2025-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionglobal',
            name='tasa_cambio_usd_mxn',
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
