# Generated by Django 5.2.4 on 2025-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionglobal',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='configuracionglobal',
            name='valor',
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='tasa_cambio_usd_mxn',
            field=models.FloatField(default=18.0, help_text='Tasa de cambio de USD a MXN'),
        ),
    ]
