# Generated by Django 5.2.3 on 2025-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='initial_message_text',
            field=models.TextField(blank=True, help_text='Primer mensaje/duda inicial del usuario.', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_display_name',
            field=models.CharField(blank=True, help_text='Nombre que el usuario proporcionó al iniciar el chat.', max_length=100, null=True),
        ),
    ]
