# Generated by Django 5.2.4 on 2025-10-06 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_proveedor_tasa_cambio_usd_mxn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name_plural': 'Mensajes del Chat'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedorprecio',
            options={'verbose_name_plural': 'Precios por Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'verbose_name_plural': 'Historial de Tipos de Cambio'},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='condicion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='modelo_fabricante',
            new_name='garantia',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_is_admin',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_display_name',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='capacidad_gb',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='compatibilidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='garantia_meses',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='memoria_gb',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='num_nucleos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_memoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_ram',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='velocidad_ghz',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='velocidad_mhz',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='divisa_defecto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='divisa_destino',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='divisa_origen',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='valor',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='tasa_usd_mxn',
            field=models.FloatField(default=18.0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tasa_cambio_usd_mxn',
            field=models.FloatField(default=18.0, help_text='Tasa global de cambio USD a MXN'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='initial_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedorprecio',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='proveedorprecio',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
