# Generated by Django 5.2.4 on 2025-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='incluye_iva',
            field=models.BooleanField(default=True, help_text='Indica si los precios del catálogo ya incluyen IVA'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='porcentaje_iva',
            field=models.FloatField(default=16.0, help_text='Porcentaje de IVA aplicable si no está incluido'),
        ),
    ]
