# Generated by Django 5.2.4 on 2025-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_proveedor_incluye_iva_proveedor_porcentaje_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
