# Generated by Django 5.2.4 on 2025-07-23 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_proveedor_tipocambio_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tasa_cambio_usd_mxn',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Tipo de cambio específico de USD a MXN para este proveedor.', max_digits=10),
        ),
    ]
