# Generated by Django 5.2.4 on 2025-07-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_proveedor_tasa_cambio_usd_mxn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
