# Generated by Django 5.2.4 on 2025-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, default='', help_text="Escribe una característica por línea (puedes iniciar con '-', '•' o '*')."),
        ),
    ]
