# Generated by Django 5.2.4 on 2025-10-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_proveedorprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_cambio_usd_mxn', models.FloatField(default=17.0)),
            ],
        ),
    ]
